### ISSUE TITLE
Cant able to generate snaphot on ios device

### ISSUE THREAD

**Issue by rajatjasuja23** [brothatru/react-video-thumbnail#7]
im trying to generate a snapshot on iphone using this library but im not able to get back the image url from the thumbnailHandler callback function, However for android i dont see this problem it works absolutely fine .On desktop its working fine.But i'm not able to understand why its not working on ios

**Comment by rakeshb-iprogrammer** [comment]
Any update on this issue?

@rajatjasuja23  did you found any solution or alternate way for this?

**Comment by akshaypjoshi** [comment]
@rajatjasuja23  @rakeshb-iprogrammer  Did you found any alternate solution?

**Comment by rakeshb-iprogrammer** [comment]
@akshaypjoshi 
I created my own component as I required few customisation in same, 
adding following highlighted to VideoThumbnail.js solved my issue for iOS device,
<video className="snapshot-generator"
                        **preload="metadata"
                        autoPlay loop muted playsInline** 



Hope this help!

**Comment by rajatjasuja23** [comment]
@akshaypjoshi  Sorry for the delay in replying, but whatever rakeshb has mentioned that's correct, In ios,
onLoadedData={() => this.setState({ dataLoaded: true })}
this piece of code won't execute and dataLoaded variable from our state always remains false which wont execute the condition in componentDidUpdate that's why it wont generate a thumbnail.

so I added, 

preload = "metadata" and 
onLoadedMetadata={() => this.setState({ metadataLoaded: true,dataLoaded: true })}



This is working for me
